// Generated by tools/generate-indic-tables.py from the Unicode Character Database.
// Do not edit by hand.

namespace Papira.Text;

/// <summary>What each character of an Indic script is, and where it goes in its syllable.</summary>
internal static class IndicTables
{
    /// <summary>First character of each run, in order; the runs cover the Indic scripts.</summary>
    public static ReadOnlySpan<int> Starts =>
    [
        0x002D, 0x0030, 0x00A0, 0x00B2, 0x00D7, 0x0900, 0x0904, 0x0915, 0x0930, 0x0931, 0x093A, 0x093C,
        0x093D, 0x093E, 0x093F, 0x0940, 0x094D, 0x094E, 0x094F, 0x0951, 0x0953, 0x0955, 0x0958, 0x0960,
        0x0962, 0x0966, 0x0972, 0x0978, 0x0980, 0x0981, 0x0985, 0x098F, 0x0993, 0x0995, 0x09AA, 0x09B0,
        0x09B2, 0x09B6, 0x09BC, 0x09BD, 0x09BE, 0x09BF, 0x09C0, 0x09C1, 0x09C7, 0x09CB, 0x09CD, 0x09CE,
        0x09D7, 0x09DC, 0x09DF, 0x09E0, 0x09E2, 0x09E6, 0x09F0, 0x09F1, 0x09FC, 0x09FE, 0x0A01, 0x0A05,
        0x0A0F, 0x0A13, 0x0A15, 0x0A2A, 0x0A30, 0x0A32, 0x0A35, 0x0A38, 0x0A3C, 0x0A3E, 0x0A3F, 0x0A40,
        0x0A41, 0x0A47, 0x0A4B, 0x0A4D, 0x0A51, 0x0A59, 0x0A5E, 0x0A66, 0x0A70, 0x0A72, 0x0A75, 0x0A81,
        0x0A85, 0x0A8F, 0x0A93, 0x0A95, 0x0AAA, 0x0AB0, 0x0AB2, 0x0AB5, 0x0ABC, 0x0ABD, 0x0ABE, 0x0ABF,
        0x0AC0, 0x0AC5, 0x0AC7, 0x0AC9, 0x0ACB, 0x0ACD, 0x0AE0, 0x0AE2, 0x0AE6, 0x0AF9, 0x0AFA, 0x0AFB,
        0x0AFC, 0x0AFD, 0x0B01, 0x0B02, 0x0B05, 0x0B0F, 0x0B13, 0x0B15, 0x0B2A, 0x0B30, 0x0B32, 0x0B35,
        0x0B3C, 0x0B3D, 0x0B3E, 0x0B3F, 0x0B40, 0x0B41, 0x0B47, 0x0B48, 0x0B4B, 0x0B4D, 0x0B53, 0x0B55,
        0x0B56, 0x0B57, 0x0B5C, 0x0B5F, 0x0B60, 0x0B62, 0x0B66, 0x0B71, 0x0B82, 0x0B85, 0x0B8E, 0x0B92,
        0x0B95, 0x0B99, 0x0B9C, 0x0B9E, 0x0BA3, 0x0BA8, 0x0BAE, 0x0BB0, 0x0BB1, 0x0BBE, 0x0BC0, 0x0BC1,
        0x0BC6, 0x0BCA, 0x0BCD, 0x0BD7, 0x0BE6, 0x0C00, 0x0C05, 0x0C0E, 0x0C12, 0x0C15, 0x0C2A, 0x0C30,
        0x0C31, 0x0C3C, 0x0C3D, 0x0C3E, 0x0C43, 0x0C46, 0x0C4A, 0x0C4D, 0x0C55, 0x0C58, 0x0C5D, 0x0C60,
        0x0C62, 0x0C66, 0x0C80, 0x0C81, 0x0C85, 0x0C8E, 0x0C92, 0x0C95, 0x0CAA, 0x0CB0, 0x0CB1, 0x0CB5,
        0x0CBC, 0x0CBD, 0x0CBE, 0x0CC3, 0x0CC6, 0x0CC7, 0x0CCA, 0x0CCC, 0x0CCD, 0x0CD5, 0x0CDD, 0x0CE0,
        0x0CE2, 0x0CE6, 0x0CF1, 0x0CF3, 0x0D00, 0x0D04, 0x0D05, 0x0D0E, 0x0D12, 0x0D15, 0x0D30, 0x0D31,
        0x0D3B, 0x0D3D, 0x0D3E, 0x0D46, 0x0D4A, 0x0D4D, 0x0D4E, 0x0D54, 0x0D57, 0x0D5F, 0x0D62, 0x0D66,
        0x0D7A, 0x1CD0, 0x1CD4, 0x1CE9, 0x1CED, 0x1CEE, 0x1CF2, 0x1CF4, 0x1CF5, 0x1CF7, 0x1CFA, 0x200C,
        0x200D, 0x2010, 0x2074, 0x2082, 0x25CC, 0xA8E0, 0xA8F2, 0xA8FE, 0xA8FF, 0x11300, 0x11305, 0x1130F,
        0x11313, 0x11315, 0x1132A, 0x11332, 0x11335, 0x1133B, 0x1133D, 0x1133E, 0x11347, 0x1134B, 0x1134D, 0x11357,
        0x1135E, 0x11360, 0x11362, 0x11366, 0x11370,
    ];

    /// <summary>Last character of each run.</summary>
    public static ReadOnlySpan<int> Ends =>
    [
        0x002D, 0x0039, 0x00A0, 0x00B3, 0x00D7, 0x0903, 0x0914, 0x092F, 0x0930, 0x0939, 0x093B, 0x093C,
        0x093D, 0x093E, 0x093F, 0x094C, 0x094D, 0x094E, 0x094F, 0x0952, 0x0954, 0x0957, 0x095F, 0x0961,
        0x0963, 0x096F, 0x0977, 0x097F, 0x0980, 0x0983, 0x098C, 0x0990, 0x0994, 0x09A8, 0x09AF, 0x09B0,
        0x09B2, 0x09B9, 0x09BC, 0x09BD, 0x09BE, 0x09BF, 0x09C0, 0x09C4, 0x09C8, 0x09CC, 0x09CD, 0x09CE,
        0x09D7, 0x09DD, 0x09DF, 0x09E1, 0x09E3, 0x09EF, 0x09F0, 0x09F1, 0x09FC, 0x09FE, 0x0A03, 0x0A0A,
        0x0A10, 0x0A14, 0x0A28, 0x0A2F, 0x0A30, 0x0A33, 0x0A36, 0x0A39, 0x0A3C, 0x0A3E, 0x0A3F, 0x0A40,
        0x0A42, 0x0A48, 0x0A4C, 0x0A4D, 0x0A51, 0x0A5C, 0x0A5E, 0x0A6F, 0x0A71, 0x0A73, 0x0A75, 0x0A83,
        0x0A8D, 0x0A91, 0x0A94, 0x0AA8, 0x0AAF, 0x0AB0, 0x0AB3, 0x0AB9, 0x0ABC, 0x0ABD, 0x0ABE, 0x0ABF,
        0x0AC4, 0x0AC5, 0x0AC8, 0x0AC9, 0x0ACC, 0x0ACD, 0x0AE1, 0x0AE3, 0x0AEF, 0x0AF9, 0x0AFA, 0x0AFB,
        0x0AFC, 0x0AFF, 0x0B01, 0x0B03, 0x0B0C, 0x0B10, 0x0B14, 0x0B28, 0x0B2F, 0x0B30, 0x0B33, 0x0B39,
        0x0B3C, 0x0B3D, 0x0B3E, 0x0B3F, 0x0B40, 0x0B44, 0x0B47, 0x0B48, 0x0B4C, 0x0B4D, 0x0B54, 0x0B55,
        0x0B56, 0x0B57, 0x0B5D, 0x0B5F, 0x0B61, 0x0B63, 0x0B6F, 0x0B71, 0x0B82, 0x0B8A, 0x0B90, 0x0B94,
        0x0B95, 0x0B9A, 0x0B9C, 0x0B9F, 0x0BA4, 0x0BAA, 0x0BAF, 0x0BB0, 0x0BB9, 0x0BBF, 0x0BC0, 0x0BC2,
        0x0BC8, 0x0BCC, 0x0BCD, 0x0BD7, 0x0BEF, 0x0C04, 0x0C0C, 0x0C10, 0x0C14, 0x0C28, 0x0C2F, 0x0C30,
        0x0C39, 0x0C3C, 0x0C3D, 0x0C42, 0x0C44, 0x0C48, 0x0C4C, 0x0C4D, 0x0C56, 0x0C5A, 0x0C5D, 0x0C61,
        0x0C63, 0x0C6F, 0x0C80, 0x0C83, 0x0C8C, 0x0C90, 0x0C94, 0x0CA8, 0x0CAF, 0x0CB0, 0x0CB3, 0x0CB9,
        0x0CBC, 0x0CBD, 0x0CC2, 0x0CC4, 0x0CC6, 0x0CC8, 0x0CCB, 0x0CCC, 0x0CCD, 0x0CD6, 0x0CDE, 0x0CE1,
        0x0CE3, 0x0CEF, 0x0CF2, 0x0CF3, 0x0D03, 0x0D04, 0x0D0C, 0x0D10, 0x0D14, 0x0D2F, 0x0D30, 0x0D3A,
        0x0D3C, 0x0D3D, 0x0D44, 0x0D48, 0x0D4C, 0x0D4D, 0x0D4E, 0x0D56, 0x0D57, 0x0D61, 0x0D63, 0x0D6F,
        0x0D7F, 0x1CD2, 0x1CE8, 0x1CEC, 0x1CED, 0x1CF1, 0x1CF3, 0x1CF4, 0x1CF6, 0x1CF9, 0x1CFA, 0x200C,
        0x200D, 0x2014, 0x2074, 0x2084, 0x25CC, 0xA8F1, 0xA8F7, 0xA8FE, 0xA8FF, 0x11303, 0x1130C, 0x11310,
        0x11314, 0x11328, 0x11330, 0x11333, 0x11339, 0x1133C, 0x1133D, 0x11344, 0x11348, 0x1134C, 0x1134D, 0x11357,
        0x1135F, 0x11361, 0x11363, 0x1136C, 0x11374,
    ];

    /// <summary>The kind of character each run holds.</summary>
    public static ReadOnlySpan<byte> Categories =>
    [
        (byte)IndicCategory.Placeholder, (byte)IndicCategory.Placeholder, (byte)IndicCategory.Placeholder, (byte)IndicCategory.SMPst, (byte)IndicCategory.Placeholder, (byte)IndicCategory.SM, (byte)IndicCategory.V, (byte)IndicCategory.C,
        (byte)IndicCategory.Ra, (byte)IndicCategory.C, (byte)IndicCategory.M, (byte)IndicCategory.N, (byte)IndicCategory.Symbol, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M,
        (byte)IndicCategory.H, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.A, (byte)IndicCategory.SM, (byte)IndicCategory.M, (byte)IndicCategory.C, (byte)IndicCategory.V,
        (byte)IndicCategory.M, (byte)IndicCategory.Placeholder, (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.Placeholder, (byte)IndicCategory.SM, (byte)IndicCategory.V, (byte)IndicCategory.V,
        (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.Ra, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.N, (byte)IndicCategory.Symbol,
        (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.H, (byte)IndicCategory.C,
        (byte)IndicCategory.M, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.V, (byte)IndicCategory.M, (byte)IndicCategory.Placeholder, (byte)IndicCategory.Ra, (byte)IndicCategory.C,
        (byte)IndicCategory.Placeholder, (byte)IndicCategory.SM, (byte)IndicCategory.SM, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.C,
        (byte)IndicCategory.Ra, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.N, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.MPst,
        (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.H, (byte)IndicCategory.M, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.Placeholder,
        (byte)IndicCategory.SM, (byte)IndicCategory.C, (byte)IndicCategory.CM, (byte)IndicCategory.SM, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.C,
        (byte)IndicCategory.C, (byte)IndicCategory.Ra, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.N, (byte)IndicCategory.Symbol, (byte)IndicCategory.M, (byte)IndicCategory.M,
        (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.H, (byte)IndicCategory.V, (byte)IndicCategory.M,
        (byte)IndicCategory.Placeholder, (byte)IndicCategory.C, (byte)IndicCategory.A, (byte)IndicCategory.N, (byte)IndicCategory.A, (byte)IndicCategory.N, (byte)IndicCategory.SM, (byte)IndicCategory.SM,
        (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.Ra, (byte)IndicCategory.C, (byte)IndicCategory.C,
        (byte)IndicCategory.N, (byte)IndicCategory.Symbol, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M,
        (byte)IndicCategory.M, (byte)IndicCategory.H, (byte)IndicCategory.M, (byte)IndicCategory.N, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.C, (byte)IndicCategory.C,
        (byte)IndicCategory.V, (byte)IndicCategory.M, (byte)IndicCategory.Placeholder, (byte)IndicCategory.C, (byte)IndicCategory.SM, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V,
        (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.Ra,
        (byte)IndicCategory.C, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.H, (byte)IndicCategory.M,
        (byte)IndicCategory.Placeholder, (byte)IndicCategory.SM, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.Ra,
        (byte)IndicCategory.C, (byte)IndicCategory.N, (byte)IndicCategory.Symbol, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.H,
        (byte)IndicCategory.M, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.V, (byte)IndicCategory.M, (byte)IndicCategory.Placeholder, (byte)IndicCategory.Placeholder, (byte)IndicCategory.SM,
        (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.Ra, (byte)IndicCategory.C, (byte)IndicCategory.C,
        (byte)IndicCategory.N, (byte)IndicCategory.Symbol, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M,
        (byte)IndicCategory.H, (byte)IndicCategory.M, (byte)IndicCategory.C, (byte)IndicCategory.V, (byte)IndicCategory.M, (byte)IndicCategory.Placeholder, (byte)IndicCategory.CS, (byte)IndicCategory.SM,
        (byte)IndicCategory.SM, (byte)IndicCategory.Placeholder, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.Ra, (byte)IndicCategory.C,
        (byte)IndicCategory.M, (byte)IndicCategory.Symbol, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.H, (byte)IndicCategory.Repha, (byte)IndicCategory.C,
        (byte)IndicCategory.M, (byte)IndicCategory.V, (byte)IndicCategory.M, (byte)IndicCategory.Placeholder, (byte)IndicCategory.C, (byte)IndicCategory.A, (byte)IndicCategory.A, (byte)IndicCategory.Symbol,
        (byte)IndicCategory.A, (byte)IndicCategory.Symbol, (byte)IndicCategory.C, (byte)IndicCategory.A, (byte)IndicCategory.CS, (byte)IndicCategory.A, (byte)IndicCategory.Placeholder, (byte)IndicCategory.ZWNJ,
        (byte)IndicCategory.ZWJ, (byte)IndicCategory.Placeholder, (byte)IndicCategory.SMPst, (byte)IndicCategory.SMPst, (byte)IndicCategory.DottedCircle, (byte)IndicCategory.A, (byte)IndicCategory.Symbol, (byte)IndicCategory.V,
        (byte)IndicCategory.M, (byte)IndicCategory.SM, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.V, (byte)IndicCategory.C, (byte)IndicCategory.C, (byte)IndicCategory.C,
        (byte)IndicCategory.C, (byte)IndicCategory.N, (byte)IndicCategory.Symbol, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.M, (byte)IndicCategory.H, (byte)IndicCategory.M,
        (byte)IndicCategory.SMPst, (byte)IndicCategory.V, (byte)IndicCategory.M, (byte)IndicCategory.A, (byte)IndicCategory.A,
    ];

    /// <summary>Where in the syllable each run belongs.</summary>
    public static ReadOnlySpan<byte> Positions =>
    [
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.AfterSub, (byte)IndicPosition.End, (byte)IndicPosition.Smvd, (byte)IndicPosition.AfterSub, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterSub,
        (byte)IndicPosition.BelowC, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterSub, (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd, (byte)IndicPosition.AfterSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.AfterSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.End, (byte)IndicPosition.Smvd,
        (byte)IndicPosition.AfterPost, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterSub, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterPost, (byte)IndicPosition.BelowC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.AfterPost, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.AfterSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.End, (byte)IndicPosition.AfterPost, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterPost,
        (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterPost, (byte)IndicPosition.BelowC, (byte)IndicPosition.BelowC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.End, (byte)IndicPosition.Smvd, (byte)IndicPosition.AfterPost, (byte)IndicPosition.PreM,
        (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterSub, (byte)IndicPosition.AfterSub, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterPost, (byte)IndicPosition.BelowC, (byte)IndicPosition.BaseC, (byte)IndicPosition.AfterPost,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.End, (byte)IndicPosition.Smvd, (byte)IndicPosition.End, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.Smvd,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.End, (byte)IndicPosition.Smvd, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterMain, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterSub, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterMain,
        (byte)IndicPosition.AfterPost, (byte)IndicPosition.BelowC, (byte)IndicPosition.AfterMain, (byte)IndicPosition.End, (byte)IndicPosition.AfterMain, (byte)IndicPosition.AfterPost, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.AfterSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AfterSub, (byte)IndicPosition.AfterPost, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AboveC, (byte)IndicPosition.AfterPost,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.End, (byte)IndicPosition.Smvd, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.AfterSub, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.AboveC,
        (byte)IndicPosition.BeforeSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.End, (byte)IndicPosition.Smvd, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.AfterSub, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.AfterSub, (byte)IndicPosition.AfterSub, (byte)IndicPosition.BeforeSub,
        (byte)IndicPosition.AboveC, (byte)IndicPosition.AfterSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BeforeSub, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd,
        (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.AfterSub, (byte)IndicPosition.Smvd, (byte)IndicPosition.AfterPost, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterPost, (byte)IndicPosition.AboveC, (byte)IndicPosition.End, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.AfterPost, (byte)IndicPosition.BaseC, (byte)IndicPosition.AfterPost, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd,
        (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.End,
        (byte)IndicPosition.End, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.AfterSub, (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC, (byte)IndicPosition.BaseC,
        (byte)IndicPosition.BaseC, (byte)IndicPosition.End, (byte)IndicPosition.Smvd, (byte)IndicPosition.AfterSub, (byte)IndicPosition.PreM, (byte)IndicPosition.AfterSub, (byte)IndicPosition.PostC, (byte)IndicPosition.AfterSub,
        (byte)IndicPosition.Smvd, (byte)IndicPosition.BaseC, (byte)IndicPosition.AfterSub, (byte)IndicPosition.Smvd, (byte)IndicPosition.Smvd,
    ];
}
