using System.Buffers.Binary;
using System.Text;

namespace Papira.Pdf;

/// <summary>
/// Builds a minimal sRGB ICC v2 display profile. PDF/A files must carry the colour profile they were
/// prepared for; generating it keeps Papira free of third-party profile files.
/// </summary>
internal static class IccProfile
{
    // sRGB primaries and white point, chromatically adapted to the D50 profile connection space.
    private static readonly (float X, float Y, float Z) WhitePoint = (0.96420f, 1.00000f, 0.82491f);
    private static readonly (float X, float Y, float Z) Red = (0.43607f, 0.22249f, 0.01392f);
    private static readonly (float X, float Y, float Z) Green = (0.38515f, 0.71687f, 0.09708f);
    private static readonly (float X, float Y, float Z) Blue = (0.14307f, 0.06061f, 0.71410f);

    public static byte[] CreateSrgb()
    {
        var tags = new List<(string Signature, byte[] Data)>
        {
            ("desc", TextDescription("sRGB IEC61966-2.1")),
            ("cprt", Text("Generated by Papira. No rights reserved.")),
            ("wtpt", Xyz(WhitePoint)),
            ("rXYZ", Xyz(Red)),
            ("gXYZ", Xyz(Green)),
            ("bXYZ", Xyz(Blue)),
            ("rTRC", Curve()),
            ("gTRC", Curve()),
            ("bTRC", Curve()),
        };

        var headerSize = 128;
        var tableSize = 4 + tags.Count * 12;
        var offset = headerSize + tableSize;

        var body = new List<byte>();
        var entries = new List<(string Signature, int Offset, int Size)>();
        foreach (var (signature, data) in tags)
        {
            entries.Add((signature, offset + body.Count, data.Length));
            body.AddRange(data);
            while (body.Count % 4 != 0)
                body.Add(0); // tags are aligned to four bytes
        }

        var total = offset + body.Count;
        var profile = new byte[total];
        var span = profile.AsSpan();

        BinaryPrimitives.WriteInt32BigEndian(span, total);
        Ascii(span[4..], "APPL");                                   // preferred CMM
        BinaryPrimitives.WriteUInt32BigEndian(span[8..], 0x02400000); // version 2.4
        Ascii(span[12..], "mntr");
        Ascii(span[16..], "RGB ");
        Ascii(span[20..], "XYZ ");
        WriteDate(span[24..], DateTime.UnixEpoch);
        Ascii(span[36..], "acsp");
        BinaryPrimitives.WriteInt32BigEndian(span[64..], 0);        // rendering intent: perceptual
        WriteXyz(span[68..], WhitePoint);

        BinaryPrimitives.WriteInt32BigEndian(span[headerSize..], tags.Count);
        for (var i = 0; i < entries.Count; i++)
        {
            var entry = span[(headerSize + 4 + i * 12)..];
            Ascii(entry, entries[i].Signature);
            BinaryPrimitives.WriteInt32BigEndian(entry[4..], entries[i].Offset);
            BinaryPrimitives.WriteInt32BigEndian(entry[8..], entries[i].Size);
        }

        body.CopyTo(profile, offset);
        return profile;
    }

    private static void Ascii(Span<byte> target, string value) => Encoding.ASCII.GetBytes(value).CopyTo(target);

    private static void WriteDate(Span<byte> target, DateTime date)
    {
        ReadOnlySpan<int> parts = [date.Year, date.Month, date.Day, date.Hour, date.Minute, date.Second];
        for (var i = 0; i < parts.Length; i++)
            BinaryPrimitives.WriteUInt16BigEndian(target[(i * 2)..], (ushort)parts[i]);
    }

    private static void WriteXyz(Span<byte> target, (float X, float Y, float Z) value)
    {
        BinaryPrimitives.WriteInt32BigEndian(target, Fixed16(value.X));
        BinaryPrimitives.WriteInt32BigEndian(target[4..], Fixed16(value.Y));
        BinaryPrimitives.WriteInt32BigEndian(target[8..], Fixed16(value.Z));
    }

    private static int Fixed16(float value) => (int)MathF.Round(value * 65536);

    private static byte[] Xyz((float X, float Y, float Z) value)
    {
        var data = new byte[20];
        Ascii(data, "XYZ ");
        WriteXyz(data.AsSpan(8), value);
        return data;
    }

    /// <summary>A gamma curve; 2.2 is close enough to the sRGB transfer function for an output intent.</summary>
    private static byte[] Curve()
    {
        var data = new byte[14];
        Ascii(data, "curv");
        BinaryPrimitives.WriteInt32BigEndian(data.AsSpan(8), 1);
        BinaryPrimitives.WriteUInt16BigEndian(data.AsSpan(12), 0x0233); // 2.2 in u8Fixed8
        return data;
    }

    private static byte[] Text(string value)
    {
        var bytes = Encoding.ASCII.GetBytes(value);
        var data = new byte[8 + bytes.Length + 1];
        Ascii(data, "text");
        bytes.CopyTo(data, 8);
        return data;
    }

    /// <summary>The ICC v2 'desc' tag: ASCII name plus empty Unicode and ScriptCode sections.</summary>
    private static byte[] TextDescription(string value)
    {
        var bytes = Encoding.ASCII.GetBytes(value);
        var data = new byte[90 + bytes.Length + 1];
        Ascii(data, "desc");
        BinaryPrimitives.WriteInt32BigEndian(data.AsSpan(8), bytes.Length + 1);
        bytes.CopyTo(data, 12);
        return data;
    }
}
