#!/usr/bin/env python3
"""Generates src/Papira/Images/Vp8Tables.cs from RFC 6386, the specification of the VP8 bitstream
that a lossy WebP picture is written in. The constants are the ones every decoder needs: the trees and
probabilities the arithmetic decoder is steered by, and the quantiser lookups.

Usage:

    curl -O https://www.rfc-editor.org/rfc/rfc6386.txt
    python3 tools/generate-vp8-tables.py rfc6386.txt src/Papira/Images/Vp8Tables.cs
"""

import re
import sys
from pathlib import Path

TABLES = [
    # (name in the RFC, name in C#, expected count, element type)
    ("kf_bmode_prob", "KeyFrameBlockModeProbabilities", 10 * 10 * 9, "byte"),
    ("coeff_update_probs", "CoefficientUpdateProbabilities", 4 * 8 * 3 * 11, "byte"),
    ("default_coeff_probs", "DefaultCoefficientProbabilities", 4 * 8 * 3 * 11, "byte"),
    ("dc_qlookup", "DcQuantizers", 128, "short"),
    ("ac_qlookup", "AcQuantizers", 128, "short"),
    ("coeff_bands", "CoefficientBands", 16, "byte"),
    ("zigzag", "Zigzag", 16, "byte"),
    ("kf_ymode_prob", "KeyFrameYModeProbabilities", 4, "byte"),
    ("kf_uv_mode_prob", "KeyFrameUvModeProbabilities", 3, "byte"),
    ("bmode_tree", "BlockModeTree", 18, "sbyte"),
    ("kf_ymode_tree", "KeyFrameYModeTree", 8, "sbyte"),
    ("uv_mode_tree", "UvModeTree", 6, "sbyte"),
    ("coeff_tree", "CoefficientTree", 22, "sbyte"),
]


def clean(text):
    text = re.sub(r"\n\x0c?[^\n]*\[Page \d+\]\n", "\n", text)
    return re.sub(r"\nRFC 6386[^\n]*\n", "\n", text)


# The trees are written with the names of the modes and tokens they lead to.
NAMES = {
    "DC_PRED": 0, "V_PRED": 1, "H_PRED": 2, "TM_PRED": 3, "B_PRED": 4,
    "B_DC_PRED": 0, "B_TM_PRED": 1, "B_VE_PRED": 2, "B_HE_PRED": 3, "B_LD_PRED": 4,
    "B_RD_PRED": 5, "B_VR_PRED": 6, "B_VL_PRED": 7, "B_HD_PRED": 8, "B_HU_PRED": 9,
    "DCT_0": 0, "DCT_1": 1, "DCT_2": 2, "DCT_3": 3, "DCT_4": 4,
    "dct_cat1": 5, "dct_cat2": 6, "dct_cat3": 7, "dct_cat4": 8, "dct_cat5": 9, "dct_cat6": 10,
    "dct_eob": 11,
}


def numbers(text, name, expected):
    """The RFC declares some tables twice: once in the prose, once in full. The full one wins."""
    best = []
    for match in re.finditer(re.escape(name), text):
        start = text.find("{", match.end())
        if start < 0:
            continue

        depth, end = 0, start
        while end < len(text):
            if text[end] == "{":
                depth += 1
            elif text[end] == "}":
                depth -= 1
                if depth == 0:
                    break
            end += 1

        body = re.sub(r"/\*.*?\*/", "", text[start:end + 1], flags=re.S)
        for symbol, value in NAMES.items():
            body = re.sub(rf"\b{symbol}\b", str(value), body)

        values = [int(value) for value in re.findall(r"-?\d+", body)]
        if len(values) == expected:
            return values

        best = values if len(values) > len(best) else best

    raise SystemExit(f"{name}: found {len(best)} values, expected {expected}")


def main():
    text = clean(Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace"))
    output = Path(sys.argv[2])

    blocks = []
    for rfc_name, name, expected, kind in TABLES:
        values = numbers(text, rfc_name, expected)
        lines = []
        for index in range(0, len(values), 16):
            lines.append("        " + " ".join(f"{value}," for value in values[index:index + 16]))

        blocks.append(f"""    /// <summary>The <c>{rfc_name}</c> table of the specification.</summary>
    public static ReadOnlySpan<{kind}> {name} =>
    [
{chr(10).join(lines)}
    ];
""")

    source = f'''// Generated by tools/generate-vp8-tables.py from RFC 6386, the VP8 bitstream specification.
// Do not edit by hand.

namespace Papira.Images;

/// <summary>
/// The constants a VP8 decoder is built on: the trees the arithmetic decoder walks, the probabilities it
/// starts from, and the tables that turn a quantiser index into a step size.
/// </summary>
internal static class Vp8Tables
{{
{chr(10).join(blocks)}}}
'''

    output.write_text(source, encoding="utf-8")
    print(f"{output}: {len(TABLES)} tables, {len(source.splitlines())} lines")


if __name__ == "__main__":
    main()
